### ISSUE TITLE
code crashes in DAVE_Init()

### ISSUE THREAD

**Issue by mm995511** [Infineon/onchipdtls-optiga-trust-x#2]
hi,
my code always crashes and jumps to the result as below
```
Default_Handler:
    b .
    .size Default_Handler, . - Default_Handler

     Insert_ExceptionHandler NMI_Handler
     Insert_ExceptionHandler HardFault_Handler
     Insert_ExceptionHandler MemManage_Handler
     Insert_ExceptionHandler BusFault_Handler
     Insert_ExceptionHandler UsageFault_Handler
     Insert_ExceptionHandler SVC_Handler
 ...
```
by tracing the code, it always occurs in the following function
```
  if (init_status == DAVE_STATUS_SUCCESS)
  {
	 /**  Initialization of INTERRUPT APP instance random_timer_intr */
	 init_status = (DAVE_STATUS_t)INTERRUPT_Init(&random_timer_intr); 
   } 
```

i am using the OPTIGA Trust X evaluation kit with DAVE 4.4.2. 
its only happens with this project.
for the get_started project its runs perfectly.
could anyone help me with this issue?
thanks a lot.

**Comment by ayushev** [comment]
Just checked out the fresh repo and repeated all the steps on the same board. Works without crashes.
Hardware:
1) https://www.infineon.com/cms/en/product/evaluation-boards/optiga-trust-x-eval-kit/
Software:
1) Fresh repository with all submodules (`--recurse-submodules` optoin shoul dbe given at clone time)
2) `Debug` Configuration for the build
3) You should see a similar [setup](https://raw.githubusercontent.com/Infineon/Assets/master/Pictures/optiga_trust_x_getstarted_import_1.jpg) prior building the project

Can you please check this setup?

regarding your log, if you don't use an optimization (for `Debug` configuration it's disabled by default) you can Step Into the function and check exactly the place where it hangs.

**Comment by mm995511** [comment]
2.Fresh repository with all submodules (--recurse-submodules optoin should be given at clone time)

it works!
thank you very much!
